[package]
edition = "2021"
name = "transcription_client"
version = "0.1.0"

[dependencies]
# simple_transcribe_rs = "1.0.1"
norma = {version = "0.0.3", features = ["metal"]}
# tokio = {version = "1.35.1", features = ["full"]}
